source 'https://rubygems.org'

gem 'rails', '3.2.9'

#database
gem 'sqlite3'

#JS
gem 'jquery-rails'
#gem "angular-rails" #rails g angular:install

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

#data access
gem 'inherited_resources'
gem 'has_scope'
gem 'responders'

#jobs
#gem 'delayed_job_active_record' #rails g delayed_job:active_record

#user access
gem 'devise' #rails g devise:install && rails g devise user && rails g devise:views
gem 'devise_invitable' #rails g devise_invitable:install && rails g devise_invitable user
gem "cancan" #rails g cancan:ability

#cron
#gem "whenever"

#uploads
gem "carrierwave" #rails g uploader Avatar
gem "fog"

#URLs
gem "friendly_id" #rails g migration AddSlugToMODEL slug #add_index :MODEL, :slug, unique: true

#administration
gem "activeadmin" #rails g active_admin:install && rails g active_admin:resource MODEL
#gem 'tinymce-rails'
#gem 'tinymce-rails-imageupload', '~> 3.5.6.3'

#pagination
gem 'kaminari' #rails g kaminari:config && rails g kaminari:views default #where 'default' is the selected theme

#server/deployment
#gem 'capistrano'
#gem 'engineyard', group: [:production, :staging]
#gem 'ey_config', group: [:production, :staging]
#gem 'newrelic_rpm', group: [:production, :staging]

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
	gem 'pry'
	gem 'pry-nav'
	gem 'pry-stack_explorer'
	#gem 'better_errors' #use this or pry but never allow this outside of :development
	gem "bullet"
	gem "guard" #guard init
	gem 'rb-fsevent', '~> 0.9.1'
	gem 'growl_notify'
end

group :development, :test do
	gem 'growl'
	#gem 'ruby_gntp'
	gem 'rspec-rails' #rails g rspec:install
	gem 'guard-rspec' #guard init rspec #config details here: https://github.com/guard/guard-rspec
	gem 'guard-spork' #guard init spork #config details here: https://github.com/guard/guard-spork
	#gem "quiet_assets"
end

group :test do
  gem "factory_girl_rails", "~> 4.1.0" #update config/application.rb to: config.generators do |g| > g.fixture_replacement :factory_girl > end
  gem "spork-rails" #spork rspec --bootstrap
  gem "webrat"
  gem "capybara"
  gem 'database_cleaner' #config details: https://github.com/bmabey/database_cleaner
  gem "json_spec" #usage: https://github.com/collectiveidea/json_spec
end